In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
## Define the vocabulary size
voc_size=10000

In [4]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8711, 6655, 3404, 3368],
 [8711, 6655, 3404, 5770],
 [8711, 1473, 3404, 1554],
 [6678, 8881, 8739, 5042, 1404],
 [6678, 8881, 8739, 5042, 8078],
 [3882, 8711, 5023, 3404, 451],
 [9856, 184, 7343, 5042]]

In [6]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [7]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8711 6655 3404 3368]
 [   0    0    0    0 8711 6655 3404 5770]
 [   0    0    0    0 8711 1473 3404 1554]
 [   0    0    0 6678 8881 8739 5042 1404]
 [   0    0    0 6678 8881 8739 5042 8078]
 [   0    0    0 3882 8711 5023 3404  451]
 [   0    0    0    0 9856  184 7343 5042]]


In [8]:
## feature representation
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 382ms/step


array([[[-0.02240216, -0.00389664,  0.01097903, -0.00056123,
          0.02108829,  0.02337754, -0.03311626, -0.03452986,
          0.04109323, -0.0343984 ],
        [-0.02240216, -0.00389664,  0.01097903, -0.00056123,
          0.02108829,  0.02337754, -0.03311626, -0.03452986,
          0.04109323, -0.0343984 ],
        [-0.02240216, -0.00389664,  0.01097903, -0.00056123,
          0.02108829,  0.02337754, -0.03311626, -0.03452986,
          0.04109323, -0.0343984 ],
        [-0.02240216, -0.00389664,  0.01097903, -0.00056123,
          0.02108829,  0.02337754, -0.03311626, -0.03452986,
          0.04109323, -0.0343984 ],
        [ 0.03581942, -0.01950523, -0.04452363,  0.0262102 ,
         -0.04112438, -0.01990213, -0.0381629 , -0.02684633,
          0.03237997, -0.02976481],
        [-0.01623512, -0.03970727,  0.00490376,  0.01797031,
         -0.04680487, -0.04032974, -0.02256798, -0.00914756,
         -0.02386041, -0.04608184],
        [-0.00538087,  0.02325984,  0.02578129, -0.0

In [12]:
embedded_docs[0]

array([   0,    0,    0,    0, 8711, 6655, 3404, 3368], dtype=int32)

In [15]:
model.predict(embedded_docs[[0]])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 207ms/step


array([[[-0.02240216, -0.00389664,  0.01097903, -0.00056123,
          0.02108829,  0.02337754, -0.03311626, -0.03452986,
          0.04109323, -0.0343984 ],
        [-0.02240216, -0.00389664,  0.01097903, -0.00056123,
          0.02108829,  0.02337754, -0.03311626, -0.03452986,
          0.04109323, -0.0343984 ],
        [-0.02240216, -0.00389664,  0.01097903, -0.00056123,
          0.02108829,  0.02337754, -0.03311626, -0.03452986,
          0.04109323, -0.0343984 ],
        [-0.02240216, -0.00389664,  0.01097903, -0.00056123,
          0.02108829,  0.02337754, -0.03311626, -0.03452986,
          0.04109323, -0.0343984 ],
        [ 0.03581942, -0.01950523, -0.04452363,  0.0262102 ,
         -0.04112438, -0.01990213, -0.0381629 , -0.02684633,
          0.03237997, -0.02976481],
        [-0.01623512, -0.03970727,  0.00490376,  0.01797031,
         -0.04680487, -0.04032974, -0.02256798, -0.00914756,
         -0.02386041, -0.04608184],
        [-0.00538087,  0.02325984,  0.02578129, -0.0